on: [push, pull_request]

name: CI

jobs:
    test:
        name: Test
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [15.x, 16.x, 17.x, 18.x]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm install
            - name: Build native module
              run: npm run build
            - name: Test
              run: npm test
